import { create } from 'zustand';

export const usePortfolioStore = create((set) => ({
  mode: 'page',
  selectedIsland: null,
  journeyTarget: null,
  dialog: null,
  activeCategory: 'featured',
  islandOnly: false,
  travelerResetToken: 0,
  miniGameOpen: false,
  worldGame: null,
  worldGameScore: 0,
  worldGameLives: 3,
  setMode: (mode) => set({ mode }),
  setActiveCategory: (activeCategory) => set({ activeCategory }),
  setIslandOnly: (islandOnly) => set({ islandOnly }),
  setMiniGameOpen: (miniGameOpen) => set({ miniGameOpen }),
  startWorldGame: () => set((state) => ({
    miniGameOpen: false,
    dialog: null,
    selectedIsland: null,
    journeyTarget: null,
    worldGame: 'obstacle',
    worldGameScore: 0,
    worldGameLives: 3,
    travelerResetToken: state.travelerResetToken + 1,
  })),
  addWorldGameScore: () => set((state) => ({ worldGameScore: state.worldGameScore + 1 })),
  hitWorldGame: () => set((state) => {
    const lives = Math.max(0, state.worldGameLives - 1);
    return { worldGameLives: lives, worldGame: lives === 0 ? 'obstacle-ended' : state.worldGame };
  }),
  stopWorldGame: () => set({ worldGame: null, worldGameScore: 0, worldGameLives: 3 }),
  startJourney: (island) => set({ selectedIsland: island, journeyTarget: island, dialog: null }),
  travelToPoint: (position) => set({ selectedIsland: null, journeyTarget: { id: 'free-travel', type: 'point', position }, dialog: null }),
  cancelJourney: () => set({ journeyTarget: null }),
  resetTraveler: () => set((state) => ({
    selectedIsland: null,
    journeyTarget: null,
    dialog: null,
    miniGameOpen: false,
    worldGame: null,
    worldGameScore: 0,
    worldGameLives: 3,
    travelerResetToken: state.travelerResetToken + 1,
  })),
  finishJourney: (island) => set({
    selectedIsland: island,
    journeyTarget: null,
    dialog: island.id === 'break' ? null : island,
    miniGameOpen: island.id === 'break',
  }),
  closeDialog: () => set({ dialog: null }),
}));
